//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopeNope.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HopeNope.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOPE or NOPE! is an application which uses the world-famous Relatio algorithm to determine whether or not a potential relationship can be iffy. If not, the app will give you the go-ahead.
        ///
        ///This app was developed as a showcase for guidoschippers.com and it&apos;s sole purpose is to demonstrate that I can create apps that require custom functionality like monetization..
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already purchased.
        /// </summary>
        internal static string AlertMessageItemAlreadyPurchased {
            get {
                return ResourceManager.GetString("AlertMessageItemAlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app needs to be rebooted in order for the changes to take effect. Do you want to continue?.
        /// </summary>
        internal static string AlertMessageRebootWarning {
            get {
                return ResourceManager.GetString("AlertMessageRebootWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AlertTitleAreYouSure {
            get {
                return ResourceManager.GetString("AlertTitleAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already purchased.
        /// </summary>
        internal static string AlertTitleItemAlreadyPurchased {
            get {
                return ResourceManager.GetString("AlertTitleItemAlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © copyright Guido Schippers.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default date of birth.
        /// </summary>
        internal static string DefaultDateOfBirth {
            get {
                return ResourceManager.GetString("DefaultDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your date&apos;s age.
        /// </summary>
        internal static string EnterDateAge {
            get {
                return ResourceManager.GetString("EnterDateAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your age.
        /// </summary>
        internal static string EnterYourAge {
            get {
                return ResourceManager.GetString("EnterYourAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading...
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ads.
        /// </summary>
        internal static string RemoveAdsTitle {
            get {
                return ResourceManager.GetString("RemoveAdsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartTitle {
            get {
                return ResourceManager.GetString("StartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum age is 16.
        /// </summary>
        internal static string ToastMessageAgeTooLow {
            get {
                return ResourceManager.GetString("ToastMessageAgeTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input an age.
        /// </summary>
        internal static string ToastMessageInputAgeEmpty {
            get {
                return ResourceManager.GetString("ToastMessageInputAgeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given input is not a valid age.
        /// </summary>
        internal static string ToastMessageInputAgeInvalidInput {
            get {
                return ResourceManager.GetString("ToastMessageInputAgeInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language set.
        /// </summary>
        internal static string ToastMessageLanguageSet {
            get {
                return ResourceManager.GetString("ToastMessageLanguageSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item purchased.
        /// </summary>
        internal static string ToastMessagePurchaseSuccess {
            get {
                return ResourceManager.GetString("ToastMessagePurchaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App succesfully reset.
        /// </summary>
        internal static string ToastMessageResetComplete {
            get {
                return ResourceManager.GetString("ToastMessageResetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase could not be verified.
        /// </summary>
        internal static string ToastMessageVerifyPurchaseInvalid {
            get {
                return ResourceManager.GetString("ToastMessageVerifyPurchaseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase succesfully verified.
        /// </summary>
        internal static string ToastMessageVerifyPurchaseSuccess {
            get {
                return ResourceManager.GetString("ToastMessageVerifyPurchaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verdict.
        /// </summary>
        internal static string Verdict {
            get {
                return ResourceManager.GetString("Verdict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify purchased item(s).
        /// </summary>
        internal static string VerifyPurchases {
            get {
                return ResourceManager.GetString("VerifyPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know you can set your date of birth in the settings page? That way can skip the first step in this wizard!.
        /// </summary>
        internal static string YourAgeShortcut {
            get {
                return ResourceManager.GetString("YourAgeShortcut", resourceCulture);
            }
        }
    }
}
