//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopeNope.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HopeNope.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOPE or NOPE! is an application which uses the world-famous Relatio algorithm to determine whether or not a potential relationship can be iffy. If not, the app will give you the go-ahead.
        ///
        ///This app was developed as a showcase for guidoschippers.com and it&apos;s sole purpose is to demonstrate that I can create apps that require custom functionality like monetization..
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to wishlist.
        /// </summary>
        internal static string AddToWishlist {
            get {
                return ResourceManager.GetString("AddToWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not supported on current device..
        /// </summary>
        internal static string AlertMessageActionNotSupported {
            get {
                return ResourceManager.GetString("AlertMessageActionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AlertMessageAreYouSure {
            get {
                return ResourceManager.GetString("AlertMessageAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera permission needed to execute the selected action..
        /// </summary>
        internal static string AlertMessageCameraPermissionNeeded {
            get {
                return ResourceManager.GetString("AlertMessageCameraPermissionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request. The developer has been notified. Please try again..
        /// </summary>
        internal static string AlertMessageErrorOccurred {
            get {
                return ResourceManager.GetString("AlertMessageErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photogallery permission needed to execute the selected action..
        /// </summary>
        internal static string AlertMessageGalleryPermissionNeeded {
            get {
                return ResourceManager.GetString("AlertMessageGalleryPermissionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already purchased.
        /// </summary>
        internal static string AlertMessageItemAlreadyPurchased {
            get {
                return ResourceManager.GetString("AlertMessageItemAlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered a name but not added the person to the wishlist. Do you want to continue?.
        /// </summary>
        internal static string AlertMessagePersonNotAddedToWishlist {
            get {
                return ResourceManager.GetString("AlertMessagePersonNotAddedToWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We tried to take the picture&apos;s date into account to determine the current age of the person depicted..
        /// </summary>
        internal static string AlertMessagePictureDateTakenIntoAccount {
            get {
                return ResourceManager.GetString("AlertMessagePictureDateTakenIntoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app needs to be rebooted in order for the changes to take effect. Do you want to continue?.
        /// </summary>
        internal static string AlertMessageRebootWarning {
            get {
                return ResourceManager.GetString("AlertMessageRebootWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage permission needed to execute the selected action..
        /// </summary>
        internal static string AlertMessageStoragePermissionNeeded {
            get {
                return ResourceManager.GetString("AlertMessageStoragePermissionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you don&apos;t want to add this person to the wishlist?.
        /// </summary>
        internal static string AlertMessageWishlistIgnoreConfirm {
            get {
                return ResourceManager.GetString("AlertMessageWishlistIgnoreConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not supported.
        /// </summary>
        internal static string AlertTitleActionNotSupported {
            get {
                return ResourceManager.GetString("AlertTitleActionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AlertTitleAreYouSure {
            get {
                return ResourceManager.GetString("AlertTitleAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera permission needed.
        /// </summary>
        internal static string AlertTitleCameraPermissionNeeded {
            get {
                return ResourceManager.GetString("AlertTitleCameraPermissionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string AlertTitleErrorOccurred {
            get {
                return ResourceManager.GetString("AlertTitleErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photogallery permission needed.
        /// </summary>
        internal static string AlertTitleGalleryPermissionNeeded {
            get {
                return ResourceManager.GetString("AlertTitleGalleryPermissionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already purchased.
        /// </summary>
        internal static string AlertTitleItemAlreadyPurchased {
            get {
                return ResourceManager.GetString("AlertTitleItemAlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture&apos;s date was taken into account.
        /// </summary>
        internal static string AlertTitlePictureDateTakenIntoAccount {
            get {
                return ResourceManager.GetString("AlertTitlePictureDateTakenIntoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage permission needed.
        /// </summary>
        internal static string AlertTitleStoragePermissionNeeded {
            get {
                return ResourceManager.GetString("AlertTitleStoragePermissionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes detected.
        /// </summary>
        internal static string AlertTitleUnsavedChanges {
            get {
                return ResourceManager.GetString("AlertTitleUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wait for {0} is over! Send {0} a message..
        /// </summary>
        internal static string CalendarItemDescriptionNopeIsHope {
            get {
                return ResourceManager.GetString("CalendarItemDescriptionNopeIsHope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Nope becomes Hope!.
        /// </summary>
        internal static string CalendarItemTitleNopeIsHope {
            get {
                return ResourceManager.GetString("CalendarItemTitleNopeIsHope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear wishlist.
        /// </summary>
        internal static string ClearWishlist {
            get {
                return ResourceManager.GetString("ClearWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © copyright guidoschippers.com.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll just have to wait for.
        /// </summary>
        internal static string Countdown {
            get {
                return ResourceManager.GetString("Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current app version.
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default date of birth.
        /// </summary>
        internal static string DefaultDateOfBirth {
            get {
                return ResourceManager.GetString("DefaultDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine by picture.
        /// </summary>
        internal static string DetermineByPicture {
            get {
                return ResourceManager.GetString("DetermineByPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update picture.
        /// </summary>
        internal static string EditPicture {
            get {
                return ResourceManager.GetString("EditPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your date&apos;s age.
        /// </summary>
        internal static string EnterDateAge {
            get {
                return ResourceManager.GetString("EnterDateAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for your wishlist.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your age.
        /// </summary>
        internal static string EnterYourAge {
            get {
                return ResourceManager.GetString("EnterYourAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine age by picture.
        /// </summary>
        internal static string FacialRecognition {
            get {
                return ResourceManager.GetString("FacialRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last attempt.
        /// </summary>
        internal static string LastAttempt {
            get {
                return ResourceManager.GetString("LastAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading...
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found.
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ads.
        /// </summary>
        internal static string RemoveAdsTitle {
            get {
                return ResourceManager.GetString("RemoveAdsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to calendar.
        /// </summary>
        internal static string SetReminder {
            get {
                return ResourceManager.GetString("SetReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartTitle {
            get {
                return ResourceManager.GetString("StartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current statistics are as follows. You can reset your statistics on the settings page..
        /// </summary>
        internal static string StatisticsDescription {
            get {
                return ResourceManager.GetString("StatisticsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View stats.
        /// </summary>
        internal static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a name.
        /// </summary>
        internal static string ToastErrorEnterName {
            get {
                return ResourceManager.GetString("ToastErrorEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person added to wishlist.
        /// </summary>
        internal static string ToastMessageAddToWishlistSuccess {
            get {
                return ResourceManager.GetString("ToastMessageAddToWishlistSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum age is 16.
        /// </summary>
        internal static string ToastMessageAgeTooLow {
            get {
                return ResourceManager.GetString("ToastMessageAgeTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input an age.
        /// </summary>
        internal static string ToastMessageInputAgeEmpty {
            get {
                return ResourceManager.GetString("ToastMessageInputAgeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given input is not a valid age.
        /// </summary>
        internal static string ToastMessageInputAgeInvalidInput {
            get {
                return ResourceManager.GetString("ToastMessageInputAgeInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language set.
        /// </summary>
        internal static string ToastMessageLanguageSet {
            get {
                return ResourceManager.GetString("ToastMessageLanguageSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item purchased.
        /// </summary>
        internal static string ToastMessagePurchaseSuccess {
            get {
                return ResourceManager.GetString("ToastMessagePurchaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App succesfully reset.
        /// </summary>
        internal static string ToastMessageResetComplete {
            get {
                return ResourceManager.GetString("ToastMessageResetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase could not be verified.
        /// </summary>
        internal static string ToastMessageVerifyPurchaseInvalid {
            get {
                return ResourceManager.GetString("ToastMessageVerifyPurchaseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase succesfully verified.
        /// </summary>
        internal static string ToastMessageVerifyPurchaseSuccess {
            get {
                return ResourceManager.GetString("ToastMessageVerifyPurchaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist cleared.
        /// </summary>
        internal static string ToastMessageWishlistCleared {
            get {
                return ResourceManager.GetString("ToastMessageWishlistCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nope to Hope on.
        /// </summary>
        internal static string UnlockDate {
            get {
                return ResourceManager.GetString("UnlockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        internal static string ValidationInvalidName {
            get {
                return ResourceManager.GetString("ValidationInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple fields are invalid.
        /// </summary>
        internal static string ValildationMultipleFieldsAreInvalid {
            get {
                return ResourceManager.GetString("ValildationMultipleFieldsAreInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verdict.
        /// </summary>
        internal static string Verdict {
            get {
                return ResourceManager.GetString("Verdict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify purchased item(s).
        /// </summary>
        internal static string VerifyPurchases {
            get {
                return ResourceManager.GetString("VerifyPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        internal static string WishlistTitle {
            get {
                return ResourceManager.GetString("WishlistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know you can set your date of birth on the settings page? That way can skip the first step in this wizard!.
        /// </summary>
        internal static string YourAgeShortcut {
            get {
                return ResourceManager.GetString("YourAgeShortcut", resourceCulture);
            }
        }
    }
}
